credentials:
  usernames:
    user1:
      email: user1@example.com
      name: User One
      password: $2b$12$kpNqQG2BGfMrK3CWIkNfXefPqYWcloj.zqgC71S9uuMTlIjjMY.eG # This is '123'
cookie:
  expiry_days: 30
  key: some_signature_key
  name: some_cookie_name
preauthorized:
  emails:
    - user1@example.com
